version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: huffmantayler1/nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    # build: 
    #   context: ./proj/backend
    #   dockerfile: Dockerfile
    image: huffmantayler1/backend:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    # build:
    #   context: ./proj/frontend
    #   dockerfile: Dockerfile
    image: huffmantayler1/frontend:latest
    restart: always
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  postgres_data:
networks:
    app-network:
