name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Runs when pushing to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag frontend image
        run: |
          echo "VITE_BACKEND_URL=http://backend:8080" >> $GITHUB_ENV
          docker build -t $DOCKER_USERNAME/frontend:latest ./proj/frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VITE_BACKEND_URL: ${{ secrets.SERVER_HOST }}:8080 

      - name: Build and tag backend image
        run: |
          docker build -t $DOCKER_USERNAME/backend:latest ./proj/backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push images to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/frontend:latest
          docker push $DOCKER_USERNAME/backend:latest
          # docker push $DOCKER_USERNAME/database:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.yml, init.sql"
          target: "/home/${{ secrets.SERVER_USER }}/app"

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
