name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Runs when pushing to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag frontend image
        run: |
          docker build -t $DOCKER_USERNAME/frontend:latest ./proj/frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build and tag backend image
        run: |
          docker build -t $DOCKER_USERNAME/backend:latest ./proj/backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # - name: Build and tag database image
      #   run: |
      #     docker build -t $DOCKER_USERNAME/database:latest ./proj/database
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push images to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/frontend:latest
          docker push $DOCKER_USERNAME/backend:latest
          # docker push $DOCKER_USERNAME/database:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

